import datetime
print("Hello world!")
now = datetime.datetime.now()
print ("Current date and time is ")
print (now.strftime("%A, %d-%m-%Y : %H:%M"))
print("new line")
print("another line")
print("hello people")
print("how are you?")
print("build")